const data = {
    products: [
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 80,
            brand: 'addidas',
            rating: 3.2,
            numReviews: 10,
            countInStock: 15,
            description: 'A popular fit shirt',
        },
        {
            name: 'Slim Shirt',
            slug: 'slim-shirt',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 90,
            brand: 'Raymond',
            rating: 4.6,
            numReviews: 5,
            countInStock: 10,
            description: 'A popular slim shirt',
        },
        {
            name: 'Golf Pants',
            slug: 'golf-pants',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price: 100,
            brand: 'Levis',
            rating: 2.8,
            numReviews: 15,
            countInStock: 50,
            description: 'Smart Looking pants',
        },
        {
            name: 'fit Pants',
            slug: 'fit-pants',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price: 100,
            brand: 'Oliver',
            rating: 2.8,
            numReviews: 15,
            countInStock: 50,
            description: 'Fit pants',
        },
        {
            name: 'classic-pants',
            slug: 'classic-pants',
            category: 'Pants',
            image: '/images/pants3.jpg',
            price: 130,
            brand: 'Casely',
            rating: 2.4,
            numReviews: 14,
            countInStock: 31,
            description: 'A classical Jeans',
        }
    ]
}

export default data;